name: Upload to Google Drive
on:
  workflow_dispatch:

jobs:
  upload-to-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Info
        id: latest_release
        run: |
          RELEASE_INFO=$(curl -sH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          VERSION=$(echo $RELEASE_INFO | jq -r .tag_name | sed 's/v//')
          
          STUDENT_URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name=="student.zip").browser_download_url')
          SOLUTION_URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name=="solution.zip").browser_download_url')
          
          if [ -z "$STUDENT_URL" ] || [ -z "$SOLUTION_URL" ]; then
            echo "Error: Missing release assets"
            exit 1
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "student_url=$STUDENT_URL" >> $GITHUB_OUTPUT
          echo "solution_url=$SOLUTION_URL" >> $GITHUB_OUTPUT

      - name: Download Release Assets
        run: |
          for file in "student.zip ${{ steps.latest_release.outputs.student_url }}" "solution.zip ${{ steps.latest_release.outputs.solution_url }}"; do
            set -- $file
            echo "Downloading $1 from $2..."
            curl -LH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o "$1" "$2"
            if ! unzip -t "$1" > /dev/null 2>&1; then
              echo "Error: $1 is not valid"
              exit 1
            fi
          done

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install google-auth google-api-python-client

      - name: Upload to Drive
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          VERSION: ${{ steps.latest_release.outputs.version }}
        run: |
          cat > upload.py << 'EOF'
          import os
          import zipfile
          from google.oauth2.credentials import Credentials
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload
          
          creds = Credentials(
              None,
              refresh_token=os.environ['REFRESH_TOKEN'],
              token_uri="https://oauth2.googleapis.com/token",
              client_id=os.environ['CLIENT_ID'],
              client_secret=os.environ['CLIENT_SECRET']
          )
          
          service = build('drive', 'v3', credentials=creds)
          folder_name = f'VCS_V1.{os.environ["VERSION"]}'
          
          folder = service.files().create(
              body={
                  'name': folder_name,
                  'mimeType': 'application/vnd.google-apps.folder',
                  'parents': [os.environ['DRIVE_FOLDER_ID']]
              },
              fields='id'
          ).execute()
          
          for zip_file in ['student.zip', 'solution.zip']:
              subfolder_name = zip_file.replace('.zip', '')
              subfolder = service.files().create(
                  body={
                      'name': subfolder_name,
                      'mimeType': 'application/vnd.google-apps.folder',
                      'parents': [folder['id']]
                  },
                  fields='id'
              ).execute()
          
              with zipfile.ZipFile(zip_file, 'r') as zip_ref:
                  zip_ref.extractall(subfolder_name)
          
              for root, dirs, files in os.walk(subfolder_name):
                  for file in files:
                      file_path = os.path.join(root, file)
                      relative_path = os.path.relpath(file_path, subfolder_name)
          
                      media = MediaFileUpload(file_path, resumable=True)
                      service.files().create(
                          body={
                              'name': relative_path,
                              'parents': [subfolder['id']]
                          },
                          media_body=media,
                          fields='id'
                      ).execute()
          
              media = MediaFileUpload(zip_file, resumable=True)
              service.files().create(
                  body={
                      'name': zip_file,
                      'parents': [folder['id']]
                  },
                  media_body=media,
                  fields='id'
              ).execute()
          EOF
          
          python upload.py

      - name: Cleanup
        if: always()
        run: |
          rm -f student.zip solution.zip
          rm -rf student solution